name: robotframework-jupyterlibrary

channels:
  - conda-forge
  - defaults

dependencies:
  - black
  - flake8
  - geckodriver
  - isort
  - jupyterlab >=0.35
  - nbsphinx
  - nodejs
  - python >=3.6
  - pillow
  - python-chromedriver-binary
  - robotframework >=3.1
  - robotframework-lint
  - robotframework-seleniumlibrary >=3.3
  - six
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - nteract_on_jupyter
